INSERT INTO AUTHORS(AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME) VALUES ('Ivan', 'Petrov');
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('Russian modern history', 1, 1);
INSERT INTO GENRES(GENRE_NAME) VALUES ('Comedy');