INSERT INTO AUTHORS(NAME) VALUES ('Ivan Petrov');
INSERT INTO GENRES(NAME) VALUES ('Comedy');
INSERT INTO BOOKS(TITLE, AUTHOR_ID, GENRE_ID) VALUES ('Russian modern history', CAST(1 AS BIGINT), CAST(1 AS BIGINT));
INSERT INTO COMMENTS(BOOK_ID, TITLE) VALUES(CAST (1 AS BIGINT), 'Test Comment');
