INSERT INTO AUTHORS(AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME) VALUES ('Ernest', 'Hemingway');
INSERT INTO AUTHORS(AUTHOR_FIRST_NAME, AUTHOR_LAST_NAME) VALUES ('Jules', 'Verne');
INSERT INTO AUTHORS(AUTHOR_FIRST_NAME, AUTHOR_SECOND_NAME, AUTHOR_LAST_NAME) VALUES ('James', 'Hadley' ,'Chase');
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('The Old Man and The Sea', 1, 1);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('The Sun Also Rises',1 , 2);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('Journey to the Centre of the Earth',2,2);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('Twenty Thousand Leagues Under the Sea',2 ,2);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('Around the World in 80 Days',2 ,2);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('The World In My Pocket',3 ,5);
INSERT INTO BOOKS(NAME, AUTHOR_ID, GENRE_ID) VALUES ('Just the Way It Is',3 ,5);

INSERT INTO GENRES(GENRE_NAME) VALUES ('Drama');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Fantasy');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Romance');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Thriller');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Crime');