DROP TABLE IF EXISTS AUTHORS ;
DROP TABLE IF EXISTS BOOKS ;
DROP TABLE IF EXISTS GENRES ;
CREATE TABLE AUTHORS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, AUTHOR_FIRST_NAME VARCHAR(255), AUTHOR_SECOND_NAME VARCHAR(255), AUTHOR_LAST_NAME VARCHAR(255));
CREATE TABLE BOOKS(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID VARCHAR (255), GENRE_ID VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT AUTO_INCREMENT PRIMARY KEY, GENRE_NAME VARCHAR(255));
