spring:
    main:
      allow-circular-references: true
      allow-bean-definition-overriding: true
    output:
      ansi:
       enabled: always
    batch:
      jdbc:
        isolation-level-for-create: SERIALIZABLE
      job:
        enabled: false
    shell:
      interactive:
        enabled: true
#    mongodb:
#      embedded:
#        version: 3.4.0
    data:
      mongodb:
        host: localhost
        port: 27017
        database: batchExportDB
      
    datasource:
      url: jdbc:h2:mem:testdb
      initialization-mode: never
    jpa:
      generate-ddl: true
      hibernate:
        ddl-auto: none
      show-sql: true
      defer-datasource-initialization: true
    h2:
     console:
       enabled: true
       path: /h2-console
       settings:
         web-allow-others: true
app:
  ages-count-to-add: 1
  input-file: entries.csv
  output-file: output.dat
  
debug: false
